spring:
  datasource:
    url: jdbc:postgresql://cockroach.domain.com:26257/fantasy_football
    hikari:
      pool-name: data-loader-local
fantasy-football-api:
  host: http://fantasy-football-web-api.domain.com