spring:
  application:
    name: fantasy-data-loader-task
  cloud:
    task:
      closecontext-enabled: true
      single-instance-enabled: true
      observation:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    hikari:
      max-pool-size: 5
      schema: dev
      data-source-properties:
        sslmode: disable