spring:
  datasource:
    url: jdbc:postgresql://postgresql.domain.com:5432/fantasy_football
    hikari:
      pool-name: data-loader-local
fantasy-football-api:
  host: http://fantasy-football-web-api.domain.com