apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fantasy-data-loader.fullname" . }}
  labels:
    {{- include "fantasy-data-loader.labels" . | nindent 4 }}
spec:
  completions: 1
  backoffLimit: 3
  activeDeadlineSeconds: 600
  parallelism: 1
  template:
    metadata:
      name: { { include "fantasy-data-loader.fullname" . } }
      labels:
        { { - include "fantasy-data-loader.labels" . | nindent 4 } }
    spec:
      containers:
        - name: fantasy-football-data-loader
          image: ghcr.io/rohanaditeya/fantasy-football-data-loader:main
          imagePullPolicy: Always
      restartPolicy: Never