name: fantasy-data-loader-build
on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  maven_clean_verify:
    name: Build and Test Repo
    if: github.ref_type == 'branch' && startsWith(github.ref_name, 'feature')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          check-latest: true
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --show-version verify
    timeout-minutes: 10
  maven_clean_deploy:
    name: Build and publish Repo
    if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'main'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          check-latest: true
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --show-version verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: downcase USER
        run: |
          echo "REPO_OWNER=${GITHUB_ACTOR,,}" >>${GITHUB_ENV}
      - name: Helm package
        uses: rarchk/action-helm-tools@1.0.15
        with:
          action: package
        env:
          CHART_DIR: ${{ github.event.repository.name }}
          ARTIFACTORY_URL: oci://${{ env.REGISTRY }}/${{ env.REPO_OWNER }}
          ARTIFACTORY_USERNAME: ${{ github.actor }}
          ARTIFACTORY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm publish artifactory
        uses: rarchk/action-helm-tools@1.0.15
        with:
          action: publish-artifactory
        env:
          CHART_DIR: ${{ github.event.repository.name }}
          ARTIFACTORY_URL: oci://${{ env.REGISTRY }}/${{ env.REPO_OWNER }}
          ARTIFACTORY_USERNAME: ${{ github.actor }}
          ARTIFACTORY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 20